server:
  port: 8088
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:123456789}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      use-redis-cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  flyway:
    locations: classpath:/db/migration, classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: ltn0Z7AAm+Rr94c7fFwsIYteMaiYVN0fz7gTbICh/ZE=

logging:
  level:
    org.springframework.security: DEBUG